# rest api looks like - http://<installation_address>/app/api/v1

name: DerScanner DAST Security Scan 1

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # - name: Download DAST CLI Tool
      #   run: |
      #     curl -o clt.jar <URL_TO_DAST_CLI>

      - name: Create DAST Project (if not exists)
        run: |
          RESPONSE=$(java -jar clt.jar -rest ${{ secrets.REST_URL }} -token ${{ secrets.API_TOKEN }} \
          dastProjectCreate -name "${{ github.event.repository.name }}:${{ github.ref_name }}")

          PROJECT_ID=$(echo $RESPONSE | jq -r '.projectUuid')
          echo "Project ID: $PROJECT_ID"
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Start DAST Scan
        run: |
          SCAN_RESPONSE=$(java -jar clt.jar -rest ${{ secrets.REST_URL }} -token ${{ secrets.API_TOKEN }} \
          dastScanCreate -url ${{ secrets.TARGET_URL }} -project $PROJECT_ID)

          SCAN_ID=$(echo $SCAN_RESPONSE | jq -r '.scanUuid')
          echo "Scan ID: $SCAN_ID"
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV

      - name: Wait for Scan to Complete
        run: |
          STATUS="running"
          while [[ "$STATUS" == "running" || "$STATUS" == "queued" ]]; do
            sleep 30
            STATUS=$(java -jar clt.jar -rest ${{ secrets.REST_URL }} -token ${{ secrets.API_TOKEN }} dastScanInfo -scan $SCAN_ID | jq -r '.status')
            echo "Scan Status: $STATUS"
          done

      - name: Export Scan Results to JSON
        run: |
          java -jar clt.jar -rest ${{ secrets.REST_URL }} -token ${{ secrets.API_TOKEN }} \
          dastExport -path ./ -project $PROJECT_ID -scans $SCAN_ID -general.format JSON

      - name: Upload Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: dast-results
          path: report.json